include(FetchContent)
FetchContent_Declare(
  gtsam
  GIT_REPOSITORY https://github.com/borglab/gtsam.git
  GIT_TAG 4.2.0
  GIT_SHALLOW TRUE
)
set(GTSAM_BUILD_TESTS OFF CACHE BOOL "" FORCE)
set(GTSAM_BUILD_EXAMPLES_ALWAYS OFF CACHE BOOL "" FORCE)
set(GTSAM_BUILD_UNSTABLE OFF CACHE BOOL "" FORCE)
set(GTSAM_BUILD_DOCS_HTML OFF CACHE BOOL "" FORCE)
set(GTSAM_USE_SYSTEM_EIGEN ON CACHE BOOL "" FORCE)
set(GTSAM_ENABLE_BOOST_SERIALIZATION OFF CACHE BOOL "" FORCE)
FetchContent_MakeAvailable(gtsam)
